# https://travis-ci.org/#!/translate/python-caighdean
sudo: false
language: python
python:
  - 2.7
install:
  - pip install --upgrade pip
  - pip install .
  - pip install caighdean[test]
  - pip freeze
  - git config --global user.email "travis@ci.com"
  - git config --global user.name "Travis Runner"

script:
  - py.test --cov-report=term --cov=. -v -s
  - flake8 --config=setup.cfg
  - codecov
